apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: shop
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:gIf8OQ==,iv:zNUfnsvvpTgoZfLHPGAKrjI9v7XlOUAfB5s1Avz5PAc=,tag:SNqtZULYw1P5al2XJyMmQw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:oqD62dype2ZXFwXvid2XphloziCFtvE=,iv:0FO7XVNcmsZ+Boyamumf2N1A/uSUootPePv2JZK/4RE=,tag:mmYa73HnMwDNq4IXSmaD7g==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:BGedig==,iv:MOVsY4/SWCWUj3YLWUH7ea5UUuHolroAfPsPqiyfwQw=,tag:Tj0Q3ZZZWMC6K8BmExFkpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycDdHL29SZDNDbXBDRzho
            Y1M4VUZmakg1aVRlQnp3YjhGTU40ejZKQVYwCjg5REdvNEdnTThmc2pHTHFGaXBG
            QTZHdVN0b0cybmxHUDJsUXNPNkw2SlkKLS0tIDg1SWk2TGh6SXN6WmRlUGRzajgv
            TTJ0UmRudGkrVFl1Q0J2alFoVDJDdTgKlS8GnaV4bi57HDW59B+vh3WbVTfiIBY4
            OLTmNE2kUANVPF5ag4sz9UkhvTLuG6nZVPk7UT+QRp4nnbsTlT76AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdvh2f5j8wqyq5jaj2ry9g3ue7fcu2x4vr635ylplqahrq2ntd2s8kta7l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:46:00Z"
    mac: ENC[AES256_GCM,data:dBFGlXyZi6tdUbAUGg7RmcYmJ0m4FOTFlpTKhcD3GupAd6HBmPug33B7UavGifnscqoomRtvEj0lCGyYP2FJ+uxp6YDVYbgnkRR7itQSNuvi2zp1TxfHzqUC2LIjNkc7oxE18HSI5qDUofdBpBu9EKC28EXrmGKII9MXAjefbX8=,iv:FSoE9qpNJM7+ghdIacIIiQl26miWgIvBgEQV862oN58=,tag:zrJRaed12jUo2Jv8GRPoMg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: ordering-secret
    namespace: shop
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:nrk/WD+u0St7zXCKDzB/0RO2HBVyCcHGwPBvulzlZT4276tNFYOyDHAjAMs7KOTX5YhGyp5ej0P661eVQ/u9A1t7Ucpohd/ppFI=,iv:kGxuy2GUhk2jT5Igl7CVpPOHLD9I9qvDdfrk+kumTOQ=,tag:mLIj9eL7j83/gpPsB8KlAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycDdHL29SZDNDbXBDRzho
            Y1M4VUZmakg1aVRlQnp3YjhGTU40ejZKQVYwCjg5REdvNEdnTThmc2pHTHFGaXBG
            QTZHdVN0b0cybmxHUDJsUXNPNkw2SlkKLS0tIDg1SWk2TGh6SXN6WmRlUGRzajgv
            TTJ0UmRudGkrVFl1Q0J2alFoVDJDdTgKlS8GnaV4bi57HDW59B+vh3WbVTfiIBY4
            OLTmNE2kUANVPF5ag4sz9UkhvTLuG6nZVPk7UT+QRp4nnbsTlT76AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdvh2f5j8wqyq5jaj2ry9g3ue7fcu2x4vr635ylplqahrq2ntd2s8kta7l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:46:00Z"
    mac: ENC[AES256_GCM,data:dBFGlXyZi6tdUbAUGg7RmcYmJ0m4FOTFlpTKhcD3GupAd6HBmPug33B7UavGifnscqoomRtvEj0lCGyYP2FJ+uxp6YDVYbgnkRR7itQSNuvi2zp1TxfHzqUC2LIjNkc7oxE18HSI5qDUofdBpBu9EKC28EXrmGKII9MXAjefbX8=,iv:FSoE9qpNJM7+ghdIacIIiQl26miWgIvBgEQV862oN58=,tag:zrJRaed12jUo2Jv8GRPoMg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: shop-secret
    namespace: shop
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:BRvbVwabq1KiQcP5C8/WgmuCRoYrLK59szNy1Jcc42Ke3VNRoAJ547DOkvgAvQ==,iv:4O9mhpNMdBgWPTs6aEdOMUkHfn/+8WhYVz7p7w9nNtg=,tag:VYo8JndkoQ8QWTcoGbkGzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycDdHL29SZDNDbXBDRzho
            Y1M4VUZmakg1aVRlQnp3YjhGTU40ejZKQVYwCjg5REdvNEdnTThmc2pHTHFGaXBG
            QTZHdVN0b0cybmxHUDJsUXNPNkw2SlkKLS0tIDg1SWk2TGh6SXN6WmRlUGRzajgv
            TTJ0UmRudGkrVFl1Q0J2alFoVDJDdTgKlS8GnaV4bi57HDW59B+vh3WbVTfiIBY4
            OLTmNE2kUANVPF5ag4sz9UkhvTLuG6nZVPk7UT+QRp4nnbsTlT76AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdvh2f5j8wqyq5jaj2ry9g3ue7fcu2x4vr635ylplqahrq2ntd2s8kta7l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:46:00Z"
    mac: ENC[AES256_GCM,data:dBFGlXyZi6tdUbAUGg7RmcYmJ0m4FOTFlpTKhcD3GupAd6HBmPug33B7UavGifnscqoomRtvEj0lCGyYP2FJ+uxp6YDVYbgnkRR7itQSNuvi2zp1TxfHzqUC2LIjNkc7oxE18HSI5qDUofdBpBu9EKC28EXrmGKII9MXAjefbX8=,iv:FSoE9qpNJM7+ghdIacIIiQl26miWgIvBgEQV862oN58=,tag:zrJRaed12jUo2Jv8GRPoMg==,type:str]
    version: 3.13.3
